#### Admins
GET http://localhost:8080/dae_project/api/admins
Accept: application/json

#### Profissionais Saude
GET http://localhost:8080/dae_project/api/profissionais
Accept: application/json

#### Doentes
GET http://localhost:8080/dae_project/api/doentes
Accept: application/json

###
POST http://localhost:8080/dae_project/api/doentes
Content-Type: application/json

{ "name": "John Doe",
  "email": "johndoe@mail.pt",
  "password": "jd"
}
