### Get JWT token
POST http://localhost:8080/dae_project/api/auth/login
Content-Type: application/json

{ "email": "pedro@mail.com",
  "password": "12345"
}

### Get JWT token
POST http://localhost:8080/dae_project/api/auth/login
Content-Type: application/x-www-form-urlencoded

email=joao@mail.pt&password=1234

### Who am I?
GET http://localhost:8080/dae_project/api/auth/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA2OTA1Nn0.TyGjhR-cWy7SiQ1jmTDPjT-_dfxSz-LQxZl6kdVTr0IscPoZ2ZtVGeu-gZH1YDZyJ73olrOHNoyvDGHW6_K5HNNWwDPz5CZiW-9ycH27tVMVDcpO0OTyTjkWXad8suBnj0_g5IM8P81KujdqULlMIU_oc7TvLgcGiUpGHZg8epMRGBJbAM_C5rYaQXiZBaBa3KKfU-Zzihz0FQQvkGx-VIDPh7kDJoGCq6B5Q7ussGq7_2VTx37y0ZE3GHB7Z3KjDHMw2oPNlCQStxHk9K9c9TeQqxxuLU-eQy2Fi1Q0SAgxqv961zsjOg0K7026vzEUAjZvoBPhrdJWzyFlSNiDVQ

##### Get doentes list
GET http://localhost:8080/dae_project/api/doentes
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA2OTA1Nn0.TyGjhR-cWy7SiQ1jmTDPjT-_dfxSz-LQxZl6kdVTr0IscPoZ2ZtVGeu-gZH1YDZyJ73olrOHNoyvDGHW6_K5HNNWwDPz5CZiW-9ycH27tVMVDcpO0OTyTjkWXad8suBnj0_g5IM8P81KujdqULlMIU_oc7TvLgcGiUpGHZg8epMRGBJbAM_C5rYaQXiZBaBa3KKfU-Zzihz0FQQvkGx-VIDPh7kDJoGCq6B5Q7ussGq7_2VTx37y0ZE3GHB7Z3KjDHMw2oPNlCQStxHk9K9c9TeQqxxuLU-eQy2Fi1Q0SAgxqv961zsjOg0K7026vzEUAjZvoBPhrdJWzyFlSNiDVQ

### Create new doente
POST http://localhost:8080/dae_project/api/doentes
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA2OTA1Nn0.TyGjhR-cWy7SiQ1jmTDPjT-_dfxSz-LQxZl6kdVTr0IscPoZ2ZtVGeu-gZH1YDZyJ73olrOHNoyvDGHW6_K5HNNWwDPz5CZiW-9ycH27tVMVDcpO0OTyTjkWXad8suBnj0_g5IM8P81KujdqULlMIU_oc7TvLgcGiUpGHZg8epMRGBJbAM_C5rYaQXiZBaBa3KKfU-Zzihz0FQQvkGx-VIDPh7kDJoGCq6B5Q7ussGq7_2VTx37y0ZE3GHB7Z3KjDHMw2oPNlCQStxHk9K9c9TeQqxxuLU-eQy2Fi1Q0SAgxqv961zsjOg0K7026vzEUAjZvoBPhrdJWzyFlSNiDVQ

{ "email": "jane@mail.com",
  "name": "Jane Doe",
  "password": "aaaa",
  "address": "Rua Teste",
  "contact": "900000001"
}

### Get a doente’s details
GET http://localhost:8080/dae_project/api/doentes/joao2@mail.pt
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA2OTA1Nn0.TyGjhR-cWy7SiQ1jmTDPjT-_dfxSz-LQxZl6kdVTr0IscPoZ2ZtVGeu-gZH1YDZyJ73olrOHNoyvDGHW6_K5HNNWwDPz5CZiW-9ycH27tVMVDcpO0OTyTjkWXad8suBnj0_g5IM8P81KujdqULlMIU_oc7TvLgcGiUpGHZg8epMRGBJbAM_C5rYaQXiZBaBa3KKfU-Zzihz0FQQvkGx-VIDPh7kDJoGCq6B5Q7ussGq7_2VTx37y0ZE3GHB7Z3KjDHMw2oPNlCQStxHk9K9c9TeQqxxuLU-eQy2Fi1Q0SAgxqv961zsjOg0K7026vzEUAjZvoBPhrdJWzyFlSNiDVQ

### Delete a doente - run after the previous POST
DELETE http://localhost:8080/dae_project/api/doentes/joao2@mail.pt
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA2OTA1Nn0.TyGjhR-cWy7SiQ1jmTDPjT-_dfxSz-LQxZl6kdVTr0IscPoZ2ZtVGeu-gZH1YDZyJ73olrOHNoyvDGHW6_K5HNNWwDPz5CZiW-9ycH27tVMVDcpO0OTyTjkWXad8suBnj0_g5IM8P81KujdqULlMIU_oc7TvLgcGiUpGHZg8epMRGBJbAM_C5rYaQXiZBaBa3KKfU-Zzihz0FQQvkGx-VIDPh7kDJoGCq6B5Q7ussGq7_2VTx37y0ZE3GHB7Z3KjDHMw2oPNlCQStxHk9K9c9TeQqxxuLU-eQy2Fi1Q0SAgxqv961zsjOg0K7026vzEUAjZvoBPhrdJWzyFlSNiDVQ
###