### Get JWT token
POST http://localhost:8080/dae_project/api/auth/login
Content-Type: application/json

{ "email": "joao@mail.com",
  "password": "1234"
}

### Get JWT token
POST http://localhost:8080/dae_project/api/auth/login
Content-Type: application/x-www-form-urlencoded

email=joao@mail.pt&password=1234

### Who am I?
GET http://localhost:8080/dae_project/api/auth/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MDk3OTY0NX0.bWlSjrOl5tgJ4zLQxSIEhIFxDc5VrypCaSOJ7xx2RWhckCL9HeEONbm4qTE7d9OkW1f8n079yv-aZ5Z6RTnyGcy2tif0-zGc4AG7ngcQw81m6bkBu95oI312jE0EDW-XG2Rec2lPW7Bow69mQsp_9IrLN4o5EA_pgFuIfsxB4gW5Xslat7ivdO8AhqiVHZCNT-Tw2dMO7RCyFPBXuK5rjgQGEfRKBXPB6xYEAbqO7FImQA-BB6fxJaSANeMGyTycAA_ziJ1b_k7PNMeHG7u4EjB1uOVR1B5lY3FPdrP0B_nOlBwlo3CpysOlJ9zh-KTSWEfQbPh1USF1Qd4J0hpMZQ

##### Get doentes list
GET http://localhost:8080/dae_project/api/doentes
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MDk3OTY0NX0.bWlSjrOl5tgJ4zLQxSIEhIFxDc5VrypCaSOJ7xx2RWhckCL9HeEONbm4qTE7d9OkW1f8n079yv-aZ5Z6RTnyGcy2tif0-zGc4AG7ngcQw81m6bkBu95oI312jE0EDW-XG2Rec2lPW7Bow69mQsp_9IrLN4o5EA_pgFuIfsxB4gW5Xslat7ivdO8AhqiVHZCNT-Tw2dMO7RCyFPBXuK5rjgQGEfRKBXPB6xYEAbqO7FImQA-BB6fxJaSANeMGyTycAA_ziJ1b_k7PNMeHG7u4EjB1uOVR1B5lY3FPdrP0B_nOlBwlo3CpysOlJ9zh-KTSWEfQbPh1USF1Qd4J0hpMZQ

### Create new doente
POST http://localhost:8080/dae_project/api/doentes
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MDk3OTY0NX0.bWlSjrOl5tgJ4zLQxSIEhIFxDc5VrypCaSOJ7xx2RWhckCL9HeEONbm4qTE7d9OkW1f8n079yv-aZ5Z6RTnyGcy2tif0-zGc4AG7ngcQw81m6bkBu95oI312jE0EDW-XG2Rec2lPW7Bow69mQsp_9IrLN4o5EA_pgFuIfsxB4gW5Xslat7ivdO8AhqiVHZCNT-Tw2dMO7RCyFPBXuK5rjgQGEfRKBXPB6xYEAbqO7FImQA-BB6fxJaSANeMGyTycAA_ziJ1b_k7PNMeHG7u4EjB1uOVR1B5lY3FPdrP0B_nOlBwlo3CpysOlJ9zh-KTSWEfQbPh1USF1Qd4J0hpMZQ

{ "email": "jane@mail.com",
  "name": "Jane Doe",
  "password": "aaaa",
  "address": "Rua Teste",
  "contact": "900000001"
}

### Get a doente’s details
GET http://localhost:8080/dae_project/api/doentes/joao2@mail.pt
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MDk3OTY0NX0.bWlSjrOl5tgJ4zLQxSIEhIFxDc5VrypCaSOJ7xx2RWhckCL9HeEONbm4qTE7d9OkW1f8n079yv-aZ5Z6RTnyGcy2tif0-zGc4AG7ngcQw81m6bkBu95oI312jE0EDW-XG2Rec2lPW7Bow69mQsp_9IrLN4o5EA_pgFuIfsxB4gW5Xslat7ivdO8AhqiVHZCNT-Tw2dMO7RCyFPBXuK5rjgQGEfRKBXPB6xYEAbqO7FImQA-BB6fxJaSANeMGyTycAA_ziJ1b_k7PNMeHG7u4EjB1uOVR1B5lY3FPdrP0B_nOlBwlo3CpysOlJ9zh-KTSWEfQbPh1USF1Qd4J0hpMZQ

### Delete a doente - run after the previous POST
DELETE http://localhost:8080/dae_project/api/doentes/joao2@mail.pt
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MDk3OTY0NX0.bWlSjrOl5tgJ4zLQxSIEhIFxDc5VrypCaSOJ7xx2RWhckCL9HeEONbm4qTE7d9OkW1f8n079yv-aZ5Z6RTnyGcy2tif0-zGc4AG7ngcQw81m6bkBu95oI312jE0EDW-XG2Rec2lPW7Bow69mQsp_9IrLN4o5EA_pgFuIfsxB4gW5Xslat7ivdO8AhqiVHZCNT-Tw2dMO7RCyFPBXuK5rjgQGEfRKBXPB6xYEAbqO7FImQA-BB6fxJaSANeMGyTycAA_ziJ1b_k7PNMeHG7u4EjB1uOVR1B5lY3FPdrP0B_nOlBwlo3CpysOlJ9zh-KTSWEfQbPh1USF1Qd4J0hpMZQ
###