### Get JWT token
POST http://localhost:8080/dae_project/api/auth/login
Content-Type: application/json

{ "email": "pedro@mail.com",
  "password": "12345"
}

### Get JWT token
POST http://localhost:8080/dae_project/api/auth/login
Content-Type: application/x-www-form-urlencoded

email=pedro@mail.pt&password=12345

### Who am I?
GET http://localhost:8080/dae_project/api/auth/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA4Mjk3Mn0.VoOUN7REGL_U4ZSi5V_2EtSkyNWhrQjLjY7Q_6tlw78iv8dR0JsS_EcDMxqMhXZPhMMGExGaotcyJGvdouEDGkE42qka-g6yXZ4cte7S_eS0WYfNRk3nzCgjZvPnQuwh7zO0RH9HQAmk0rgquBVuuX0fI53MmH6ovMPy1BJXemAbPAYeL0biVU949bKPf8GLd_rOPDJtzNGZSBXuCWoiq68xIyMmY6o-TPaCOFFFwUnEGJIQhWjA27kFRG_Olv8HEO9pHgELE_n2Uk-D4p6OWARNvSfVSGjqy8sCDuSYlciPL3lHCJwx08kayb5C9xRdQaeO-YxlXsRFtRm7Iq713g

##### Get doentes list
GET http://localhost:8080/dae_project/api/doentes
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA4Mjk3Mn0.VoOUN7REGL_U4ZSi5V_2EtSkyNWhrQjLjY7Q_6tlw78iv8dR0JsS_EcDMxqMhXZPhMMGExGaotcyJGvdouEDGkE42qka-g6yXZ4cte7S_eS0WYfNRk3nzCgjZvPnQuwh7zO0RH9HQAmk0rgquBVuuX0fI53MmH6ovMPy1BJXemAbPAYeL0biVU949bKPf8GLd_rOPDJtzNGZSBXuCWoiq68xIyMmY6o-TPaCOFFFwUnEGJIQhWjA27kFRG_Olv8HEO9pHgELE_n2Uk-D4p6OWARNvSfVSGjqy8sCDuSYlciPL3lHCJwx08kayb5C9xRdQaeO-YxlXsRFtRm7Iq713g

### Create new doente
POST http://localhost:8080/dae_project/api/doentes
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA4Mjk3Mn0.VoOUN7REGL_U4ZSi5V_2EtSkyNWhrQjLjY7Q_6tlw78iv8dR0JsS_EcDMxqMhXZPhMMGExGaotcyJGvdouEDGkE42qka-g6yXZ4cte7S_eS0WYfNRk3nzCgjZvPnQuwh7zO0RH9HQAmk0rgquBVuuX0fI53MmH6ovMPy1BJXemAbPAYeL0biVU949bKPf8GLd_rOPDJtzNGZSBXuCWoiq68xIyMmY6o-TPaCOFFFwUnEGJIQhWjA27kFRG_Olv8HEO9pHgELE_n2Uk-D4p6OWARNvSfVSGjqy8sCDuSYlciPL3lHCJwx08kayb5C9xRdQaeO-YxlXsRFtRm7Iq713g

{ "email": "jane@mail.com",
  "name": "Jane Doe",
  "password": "aaaa",
  "address": "Rua Teste",
  "contact": "900000001"
}

### Get a doente’s details
GET http://localhost:8080/dae_project/api/doentes/joao2@mail.pt
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA4Mjk3Mn0.VoOUN7REGL_U4ZSi5V_2EtSkyNWhrQjLjY7Q_6tlw78iv8dR0JsS_EcDMxqMhXZPhMMGExGaotcyJGvdouEDGkE42qka-g6yXZ4cte7S_eS0WYfNRk3nzCgjZvPnQuwh7zO0RH9HQAmk0rgquBVuuX0fI53MmH6ovMPy1BJXemAbPAYeL0biVU949bKPf8GLd_rOPDJtzNGZSBXuCWoiq68xIyMmY6o-TPaCOFFFwUnEGJIQhWjA27kFRG_Olv8HEO9pHgELE_n2Uk-D4p6OWARNvSfVSGjqy8sCDuSYlciPL3lHCJwx08kayb5C9xRdQaeO-YxlXsRFtRm7Iq713g

### Delete a doente - run after the previous POST
DELETE http://localhost:8080/dae_project/api/doentes/joao2@mail.pt
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2FvQG1haWwucHQiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiRG9lbnRlIl0sImV4cCI6MTY0MTA4Mjk3Mn0.VoOUN7REGL_U4ZSi5V_2EtSkyNWhrQjLjY7Q_6tlw78iv8dR0JsS_EcDMxqMhXZPhMMGExGaotcyJGvdouEDGkE42qka-g6yXZ4cte7S_eS0WYfNRk3nzCgjZvPnQuwh7zO0RH9HQAmk0rgquBVuuX0fI53MmH6ovMPy1BJXemAbPAYeL0biVU949bKPf8GLd_rOPDJtzNGZSBXuCWoiq68xIyMmY6o-TPaCOFFFwUnEGJIQhWjA27kFRG_Olv8HEO9pHgELE_n2Uk-D4p6OWARNvSfVSGjqy8sCDuSYlciPL3lHCJwx08kayb5C9xRdQaeO-YxlXsRFtRm7Iq713g
###